### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by cmeury**
@iMartyn This PR does things differently than your contribution, superseding #1. Do you think it makes sense?

### CODE REVIEW

**Comment by iMartyn** [comment]
I like it, let's get it upstream too.

**Comment by cmeury** [comment]
@iMartyn Yeah, I opened a PR over there - but no reaction so far. Since you forked from my fork I thought we're going to establish this one as the current up-to-date fork :)

**Comment by iMartyn** [comment]
I think I did that by accident! I looked at PRs, saw none, assumed you hadn't opened a PR, and clearly got lost along the way.

**Comment by cmeury** [comment]
Ah, I see :D So I'll go ahead and close this one, in favor of https://github.com/blendle/kns/pull/3

**Pull request closed without merging**
